/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransferenciaRouteImport } from './routes/_authenticated/transferencia'
import { Route as AuthenticatedSaquesRouteImport } from './routes/_authenticated/saques'
import { Route as AuthenticatedExtratoRouteImport } from './routes/_authenticated/extrato'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransferenciaRoute =
  AuthenticatedTransferenciaRouteImport.update({
    id: '/transferencia',
    path: '/transferencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaquesRoute = AuthenticatedSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtratoRoute = AuthenticatedExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/saques': typeof AuthenticatedSaquesRoute
  '/transferencia': typeof AuthenticatedTransferenciaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/saques': typeof AuthenticatedSaquesRoute
  '/transferencia': typeof AuthenticatedTransferenciaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/extrato': typeof AuthenticatedExtratoRoute
  '/_authenticated/saques': typeof AuthenticatedSaquesRoute
  '/_authenticated/transferencia': typeof AuthenticatedTransferenciaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/extrato' | '/saques' | '/transferencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/extrato' | '/saques' | '/transferencia' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/extrato'
    | '/_authenticated/saques'
    | '/_authenticated/transferencia'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencia': {
      id: '/_authenticated/transferencia'
      path: '/transferencia'
      fullPath: '/transferencia'
      preLoaderRoute: typeof AuthenticatedTransferenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saques': {
      id: '/_authenticated/saques'
      path: '/saques'
      fullPath: '/saques'
      preLoaderRoute: typeof AuthenticatedSaquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrato': {
      id: '/_authenticated/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AuthenticatedExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExtratoRoute: typeof AuthenticatedExtratoRoute
  AuthenticatedSaquesRoute: typeof AuthenticatedSaquesRoute
  AuthenticatedTransferenciaRoute: typeof AuthenticatedTransferenciaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExtratoRoute: AuthenticatedExtratoRoute,
  AuthenticatedSaquesRoute: AuthenticatedSaquesRoute,
  AuthenticatedTransferenciaRoute: AuthenticatedTransferenciaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
